using Newtonsoft.Json;
namespace AutoGeniusSync.DTOs;
public class VsrValue
{
    [JsonProperty("DealerName")]    public string? DealerName { get; set; }
    [JsonProperty("DealerCode")]           public string? DealerCode { get; set; }
    [JsonProperty("InvoiceNo")]            public string? InvoiceNo { get; set; }
    [JsonProperty("InvoiceDate")]          public string? InvoiceDate { get; set; }
    [JsonProperty("Location")]              public string? Location { get; set; }
    [JsonProperty("LocCode")]              public string? LocCode { get; set; }
    [JsonProperty("LocationCity")]         public string? LocationCity { get; set; }
    [JsonProperty("CustDOB")]              public string? CustDOB { get; set; }
    [JsonProperty("Gender")]                public string? Gender { get; set; }
    [JsonProperty("SoldTo")]               public string? SoldTo { get; set; }
    [JsonProperty("AccountType")]          public string? AccountType { get; set; }
    [JsonProperty("PartyEmail")]           public string? PartyEmail { get; set; }
    [JsonProperty("CusMob")]               public string? CusMob { get; set; }
    [JsonProperty("Address1")]              public string? Address1 { get; set; }
    [JsonProperty("Address2")]              public string? Address2 { get; set; }
    [JsonProperty("City")]                  public string? City { get; set; }
    [JsonProperty("State")]                 public string? State { get; set; }
    [JsonProperty("ExecutiveName")]        public string? ExecutiveName { get; set; }
    [JsonProperty("Pin")]                   public string? Pin { get; set; }
    [JsonProperty("ChassisNo")]             public string? ChassisNo { get; set; }
    [JsonProperty("MotorNo")]              public string? MotorNo { get; set; }
    [JsonProperty("Remarks")]               public string? Remarks { get; set; }
    [JsonProperty("ItemModel")]            public string? ItemModel { get; set; }
    [JsonProperty("OEMModel")]             public string? OEMModel { get; set; }
    [JsonProperty("ColorCode")]            public string? ColorCode { get; set; }
    [JsonProperty("VehicleType")]                  public string? VehicleType { get; set; }
    [JsonProperty("VehicleGroup")]                 public string? VehicleGroup { get; set; }
    [JsonProperty("HSNSACCode")]           public string? HSNSACCode { get; set; }
    [JsonProperty("SaleType")]             public string? SaleType { get; set; }
    [JsonProperty("FinancedBy")]           public string? FinancedBy { get; set; }
    [JsonProperty("FinAmount")]              public string? FinAmount { get; set; }
    [JsonProperty("ItemRate")]             public string? ItemRate { get; set; }
    [JsonProperty("InsuAmount")]            public string? InsuAmount { get; set; }
    [JsonProperty("RegnAmount")]            public string? RegnAmount { get; set; }
    [JsonProperty("AcsryAmount")]           public string? AcsryAmount { get; set; }
    [JsonProperty("PreGSTDiscAmount")]     public string? PreGSTDiscAmount { get; set; }
    [JsonProperty("DiscTypeName")]         public string? DiscTypeName { get; set; }
    [JsonProperty("PostGSTDisc")]        public string? PostGSTDisc { get; set; }
    [JsonProperty("FameII")]               public string? FameII { get; set; }
    [JsonProperty("StateFameII")]         public string? StateFameII { get; set; }
    [JsonProperty("SGSTPer")]              public string? SGSTPer { get; set; }
    [JsonProperty("SGSTAmount")]             public string? SGSTAmount { get; set; }
    [JsonProperty("CGSTPer")]              public string? CGSTPer { get; set; }
    [JsonProperty("CGSTAmount")]             public string? CGSTAmount { get; set; }
    [JsonProperty("IGSTPer")]              public string? IGSTPer { get; set; }
    [JsonProperty("IGSTAmount")]             public string? IGSTAmount { get; set; }
    [JsonProperty("NetAmount")]              public string? NetAmount { get; set; }
    [JsonProperty("ReferenceNo")]          public string? ReferenceNo { get; set; }
    [JsonProperty("BookingDate")]          public string? BookingDate { get; set; }
    [JsonProperty("TotalCount")]                 public string? TotalCount { get; set; }
    [JsonProperty("Battery")]               public string? Battery { get; set; }
    [JsonProperty("BatteryChemical")]      public string? BatteryChemical { get; set; }
    [JsonProperty("BatteryCapacity")]      public string? BatteryCapacity { get; set; }
    [JsonProperty("BatteryMake")]          public string? BatteryMake { get; set; }
    [JsonProperty("ChargerNo")]            public string? ChargerNo { get; set; }
    [JsonProperty("ChargerNo2")]           public string? ChargerNo2 { get; set; }
    [JsonProperty("Converter")]             public string? Converter { get; set; }
    [JsonProperty("VCU")]                   public string? VCU { get; set; }
    [JsonProperty("ControllerNo")]         public string? ControllerNo { get; set; }
    [JsonProperty("FameIIRequired")]       public string? FameIIRequired { get; set; }
    [JsonProperty("SegmentName")]          public string? SegmentName { get; set; }
    [JsonProperty("InstitutionalName")]    public string? InstitutionalName { get; set; }
    [JsonProperty("SchemeName")]           public string? SchemeName { get; set; }
}
